version: "3.7"
networks:
  network-arqui:
    name: network-arqui
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_URL: ${POSTGRES_URL}
    volumes:
      - .\\init.sql:/docker-entrypoint-initdb.d/init.sql
      - D:\\Arquitectura Software\\volumenes\\postgres\\data:/var/lib/postgresql/data
    networks:
      - network-arqui

  keycloak-postgres:
    container_name: keycloak-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PORT: ${KEYCLOAK_POSTGRES_PORT}
      POSTGRES_USERNAME: ${KEYCLOAK_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB}
      POSTGRES_URL: ${KEYCLOAK_POSTGRES_URL}
    volumes:
      - D:\\Arquitectura Software\\volumenes\\keycloak\\postgres\\data:/var/lib/postgresql/data
    networks:
      - network-arqui

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.2
    user: root
    command: start-dev
    restart: always
    ports:
      - "8090:8090"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_PORT: ${KEYCLOAK_PORT}
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-postgres
      KC_DB_URL_DATABASE: ${KEYCLOAK_POSTGRES_DB}
      KC_DB_USERNAME: ${KEYCLOAK_POSTGRES_USERNAME}
      KC_DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
      KC_DB_SCHEMA: public
    volumes:
      - D:\\Arquitectura Software\\volumenes\\keycloak\\data:/opt/keycloak/data
    networks:
      - network-arqui
    depends_on:
      - keycloak-postgres

  backend:
    container_name: dog-backend
    image: backend:0.1.1
    restart: always
    ports:
      - "8080:8080"
    environment:
      PORT: ${BACKEND_PORT}
      DB_URL: ${BACKEND_DB_URL}
      DB_USERNAME: ${BACKEND_DB_USERNAME}
      DB_PASSWORD: ${BACKEND_DB_PASSWORD}
      ISSUER_URI: ${BACKEND_ISSUER_URI}
      RESOURCE_ID: ${BACKEND_RESOURCE_ID}
    volumes:
      - D:\\Arquitectura Software\\volumenes\\backend\\logs:/opt/arqui/logs
    depends_on:
      - postgres
      - keycloak
    networks:
      - network-arqui

  frontend:
    container_name: dog-frontend
    image: frontend:0.1.1
    restart: always
    ports:
      - "4200:80"
    volumes:
      - D:\\Arquitectura Software\\volumenes\\frontend\\nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - keycloak
      - backend
    networks:
      - network-arqui